const games=[
{id:'minecraft',name:'Minecraft',title:'MINECRAFT',type:'自由建造',genre:'自由建造 / 生存探險',maker:'Mojang Studios',tag:'給想慢慢蓋一個家的人',line:'再放一塊方塊，<br>今天就先不下線。',quote:'世界再大，也想有一間亮著燈的小屋。',intro:'由方塊組成的沙盒世界。從空手採集到打造自己的基地，可以在生存模式探索與冒險，也能在創造模式專心實現腦中的建築。',steps:['採集木材、製作工具，先為第一個夜晚找個落腳處。','探索洞穴與不同地形，把資源帶回來，慢慢擴建自己的家。','想純粹創作時，切換創造模式，讓想像力決定下一塊方塊。'],why:'喜歡它把目標交給玩家。今天可以認真探礦，明天也可以只修一條通往海邊的小路。每一點改變都留在自己的世界裡。',note:'我最喜歡的不是把房子蓋得多大，而是替窗邊加一盞燈、整理門口的田。探索很遠之後再看見家的輪廓，那種安心感，就是我想一直回來的原因。',url:'https://www.minecraft.net/en-us/about-minecraft',source:'Minecraft 官方介紹'},
{id:'pvz',name:'Plants vs. Zombies',title:'PLANTS vs. ZOMBIES',type:'輕鬆策略',genre:'草坪塔防 / 資源配置',maker:'PopCap Games',tag:'給喜歡邊放鬆邊動腦的人',line:'陽光收好了，<br>草坪就交給我。',quote:'再混亂的日子，也要把向日葵種好。',intro:'殭屍沿著草坪的路線步步逼近，你要用植物組成防線。可愛外表下，是陽光資源、種植位置與出手時機的策略取捨。',steps:['種向日葵並收集陽光，建立能持續種植的資源來源。','在不同路線安排豌豆射手與堅果，兼顧火力和阻擋。','觀察特殊殭屍與場地，調整植物組合，留下應急手段。'],why:'規則很快就懂，組合卻一直有趣。短短一關就能體驗規劃、防守與臨場補救，適合想玩一點、又想動點腦的時候。',note:'我總想把草坪排得整整齊齊，但最有趣的偏偏是防線差一點崩掉的時候。手忙腳亂補上一顆堅果，然後看著最後一隻殭屍倒下，真的會鬆一口氣。',url:'https://store.steampowered.com/app/3590/Plants_vs_Zombies_GOTY_Edition/',source:'Steam 遊戲介紹'},
{id:'hollow',name:'Hollow Knight',title:'HOLLOW KNIGHT',type:'探索挑戰',genre:'銀河惡魔城 / 精準戰鬥',maker:'Team Cherry',tag:'給願意再試一次的人',line:'迷路也沒關係，<br>這裡的風景值得。',quote:'在寂靜的地下王國，找到自己的勇氣。',intro:'深入名為聖巢的昆蟲王國，在手繪的洞穴與失落城市中探索。這是一場結合平台跳躍、近身戰鬥與地圖探索的 2D 冒險。',steps:['觀察敵人的動作，以骨釘攻擊，搭配跳躍與衝刺閃避。','尋找地圖、捷徑和休息長椅，逐漸串起地下世界。','獲得新能力並搭配護符，回頭探索原本到不了的路。'],why:'喜歡地圖慢慢連成一體的感覺，也喜歡戰鬥要求的耐心。音樂和留白讓每座城市都有情緒，即使停下來也不會覺得無聊。',note:'對我來說，最好的進步不是突然變強，而是原本慌張的招式終於看懂了。打不過就先去別的地方走走，再回來試一次；長椅旁的片刻安靜，也成了冒險的一部分。',url:'https://store.steampowered.com/app/367520/Hollow_Knight/',source:'Steam 遊戲介紹'},
{id:'zelda',name:'薩爾達傳說 曠野之息',title:'BREATH OF THE WILD',type:'自由冒險',genre:'開放世界 / 探索解謎',maker:'Nintendo',tag:'給總是被遠方吸引的人',line:'目的地先等等，<br>我想去那座山。',quote:'走偏的那條路，往往才是旅行的開始。',intro:'在廣闊的海拉魯甦醒，扮演林克自由探索山川與遺跡。攀爬、滑翔、料理和環境互動，讓前往目的地的過程充滿自己的解法。',steps:['觀察地形、規劃體力，用攀爬與滑翔找到自己的路。','探索神廟，嘗試運用能力與環境解開機關。','收集食材與裝備，依天氣、地形和敵人調整準備。'],why:'它讓好奇心成為最可靠的導航。遠處奇怪的石頭、山頂的景色，都可能比原先要去的地方更吸引人。',note:'我喜歡先挑一個遠方的輪廓，再想辦法走過去。途中被一座神廟、一場雨或一匹馬岔開，反而覺得這才像冒險。沒有照計畫走，也可以是很充實的一趟旅程。',url:'https://www.nintendo.com/us/store/products/the-legend-of-zelda-breath-of-the-wild-us/',source:'Nintendo 官方介紹',original:'ゼルダの伝説 ブレス オブ ザ ワイルド'},
{id:'witcher',name:'The Witcher 3: Wild Hunt',title:'THE WITCHER 3',type:'劇情沉浸',genre:'角色扮演 / 敘事冒險',maker:'CD PROJEKT RED',tag:'給願意聽完一段故事的人',line:'收起銀劍之前，<br>先聽聽他的故事。',quote:'比怪物更難看清的，是人心。',intro:'扮演獵魔士傑洛特，在戰亂中的奇幻世界尋找希里。追查線索、接受委託與面對抉擇，交織成充滿人物故事的角色扮演冒險。',steps:['運用獵魔士感官追查線索，了解委託背後的原因。','準備劍油、藥水與法印，針對敵人特性安排戰鬥。','仔細聽對話，再決定如何回應；選擇可能留下後續影響。'],why:'吸引我的是任務背後的人。看似普通的委託常常走向意想不到的處境，讓戰鬥之外的對話也值得慢下來。',note:'我喜歡在接委託之前先把村子逛一遍。理解一個人的處境後，選項就不再只是獎勵多或少。有時候做完決定還會想很久，這種餘韻讓世界變得有重量。',url:'https://www.thewitcher.com/us/en/witcher3',source:'The Witcher 3 官方網站'}
];
let selected=0;
const $=s=>document.querySelector(s);
$('#cartridges').innerHTML=games.map((g,i)=>`<button class="cartridge" aria-pressed="${i===0}" data-index="${i}" aria-label="閱讀 ${g.name} 的收藏筆記"><img src="assets/${g.id}.jpg" alt="" width="460" height="215" loading="lazy"><strong>${g.name}</strong><small>${g.type}</small></button>`).join('');
function selectGame(i){selected=(i+games.length)%games.length;const g=games[selected];$('#hero-image').src=`assets/${g.id}.jpg`;$('#hero-image').alt=`${g.name} 遊戲世界`;$('#hero-title').textContent=g.title;$('#hero-tag').textContent=g.tag;$('#hero-line').innerHTML=g.line;$('#hero-caption').textContent=g.genre;$('#screen-number').textContent=`0${selected+1} / 05`;$('#note-type').textContent=g.type;document.querySelectorAll('.cartridge').forEach((b,n)=>b.setAttribute('aria-pressed',String(n===selected)));$('#game-detail').innerHTML=`<header class="note-header"><span class="sub">${g.maker}${g.original?`<br>${g.original}`:''}</span><h3>${g.name}</h3><p>${g.quote}</p></header><div class="note-block"><h4>遊戲介紹</h4><p>${g.intro}</p></div><div class="note-block"><h4>怎麼玩</h4><ul class="play-steps">${g.steps.map(s=>`<li>${s}</li>`).join('')}</ul></div><div class="note-block"><h4>為什麼放進收藏</h4><p>${g.why}</p></div><div class="note-block impression"><h4>我的遊玩心得</h4><p>${g.note}</p></div><div class="note-source"><a href="${g.url}" target="_blank" rel="noopener noreferrer">${g.source} ↗</a><small>心得示範稿 · 可換成你的故事</small></div>`;}
$('#cartridges').addEventListener('click',e=>{const b=e.target.closest('[data-index]');if(b)selectGame(Number(b.dataset.index));});
$('#prev').addEventListener('click',()=>selectGame(selected-1));$('#next').addEventListener('click',()=>selectGame(selected+1));
$('#hero-read').addEventListener('click',()=>{$('#notes').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});$('#notes-heading').tabIndex=-1;$('#notes-heading').focus({preventScroll:true});});
selectGame(0);
